# OMEGA Engine Constants

# Hitter Smash Gate Thresholds
SMASH_XWOBA_THRESHOLD = 0.360
SMASH_PLATOON_THRESHOLD = 1.03

# Pitcher Dominance Thresholds
SP_DOMINANCE_THRESHOLD = 80.0
SP_DOMINANCE_FACTOR = 0.5

# Weather & Umpire Sentiment Limits
UMPIRE_NEUTRAL_FACTOR = 1.0
WEATHER_BOOST_DAMPENER = 100.0

# Vegas Implied Total & Over/Under Divergence Thresholds
VEGAS_ITT_LOW_THRESHOLD = 4.0
VEGAS_ITT_HIGH_THRESHOLD = 5.5
UNDER_DIVERGENCE_HIGH = 15
UNDER_DIVERGENCE_LOW = 10
OVER_DIVERGENCE_HIGH = 15
OVER_DIVERGENCE_LOW = 8

# GPP Sneaky Stack Thresholds
SNEAKY_STACK_PREMIUM = 4.0
GASSED_BULLPEN_PREMIUM = 8.0
ANTI_CHALK_SMASH_PREMIUM = 10.0
PITCH_ALIGNMENT_PREMIUM = 4.0
